- defaults:
    link:
        relink: true

- clean: ['~']

- link:
    ~/.bashrc: bash/bashrc
    ~/.bash_profile: bash/bashrc
    ~/.tmux.conf: tmux/tmux.conf
    ~/.gitconfig: git/gitconfig
    ~/.config/htop/htoprc: top/htoprc
    ~/.profile.d/load: shell/load
    ~/.profile.d/20-aliases.sh: shell/aliases.sh

- shell:
  - [git submodule update --init --recursive, Installing submodules]
